### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by afm-sayem** [open-iut/website#1]

**Comment by maxto024** [comment]
did you setup continuous integration  or still you are doing if you did that great if not i am  familiar with https://www.atlassian.com/software/bamboo   bamboo is one of the best continuous integration out there  in our company i setup complete development environment  jira bamboo bitbucket  if you need any help i can do that 
you can check our integration   that i setup before  thanks
http://bamboo.luulsolutions.com:8085/

**Comment by afm-sayem** [comment]
Hey could you setup using [CircleCI](https://circleci.com) or [Travis](https://travis-ci.org/)? Unlike bamboo, their free tiers are not time limited. They are also much prominent in open source projects so configurations and tutorials can be found plenty.

**Comment by maxto024** [comment]
yes i can specially Travis  but do we want self hosted or we can use Travis CI

**Comment by maxto024** [comment]
I setup account in Travis and i create repository  from  open-iut/website that i forked  in here  
you can check in [here](https://travis-ci.org/maxto024/website)  I am following this [document](https://docs.travis-ci.com/user/languages/python/)  to allow continuously build  python

**Comment by afm-sayem** [comment]
That's great! Initially, we want only want to deploy to Heroku on any commits on master. We can add more tasks like minification, tests later.

According to [the docs](https://docs.travis-ci.com/user/deployment/heroku/), you'll need the API key to current Heroku application in order to deploy from Travis. If you drop your email here I can mail you the encrypted key that you can use to test whether deployment is working or not.

**Comment by maxto024** [comment]
ok here is my email
maxto024@gmail.com

**Comment by afm-sayem** [comment]
@maxto024 I just noticed that Heroku has automated deployment integration baked in with Github. All I needed to do is turn on a flag and it'll do automatic deployment from master.

I think that resolves the ticket for now. In near future when we start writing tests and start optimizing static resources, we will revisit this. Sounds good?

**Comment by maxto024** [comment]
Yeah  that's great.  Ok
